### ISSUE TITLE
ReadTheDocs build fails

### ISSUE THREAD

**Issue by jonas-eschle** [zfit/phasespace#67]
As mentioned in #66 the RTD docs fails: https://readthedocs.org/projects/phasespace/builds/15190928/

**Comment by redeboer** [comment]
Initially, I thought it is because RTD does not have GPU. It's weird though that this wasn't a problem before. Perhaps a consequence of using TF 2.7?

**Comment by jonas-eschle** [comment]
It was a problem already, it started failing a while ago. I initially thought that it is just a "temporary" failure (a dependency that has a problem or similar) but turns out it's not.
The GPU should not be a problem, TF runs as well on machines without

**Comment by redeboer** [comment]
> TF runs as well on machines without

True, but there are some cuda warnings that (I think) can be suppressed if you install `tensorflow-cpu`. I thought perhaps those warnings are [treated as errors](https://github.com/zfit/phasespace/blob/acbd6b9/.readthedocs.yml#L15) on RTD since TF2.7. But if this was there before #66, this can't be the issue.

**Comment by jonas-eschle** [comment]
Hm, but that would fail louder I hope... The first time it failed was in #58 , which clearly didn't do any real changes. That's why my thought was that it was because of a dependency or similar
